// База данных героев Dota 2 - Lap Fortuna
// Все герои с уникальными именами и путями к изображениям

const heroes = [
    { name: "Abaddon", image: "heroes/abaddon.png" },
    { name: "Alchemist", image: "heroes/alchemist.png" },
    { name: "Ancient Apparition", image: "heroes/ancient_apparition.png" },
    { name: "Anti-Mage", image: "heroes/antimage.png" },
    { name: "Arc Warden", image: "heroes/arc_warden.png" },
    { name: "Axe", image: "heroes/axe.png" },
    { name: "Bane", image: "heroes/bane.png" },
    { name: "Batrider", image: "heroes/batrider.png" },
    { name: "Beastmaster", image: "heroes/beastmaster.png" },
    { name: "Bloodseeker", image: "heroes/bloodseeker.png" },
    { name: "Bounty Hunter", image: "heroes/bounty_hunter.png" },
    { name: "Brewmaster", image: "heroes/brewmaster.png" },
    { name: "Bristleback", image: "heroes/bristleback.png" },
    { name: "Broodmother", image: "heroes/broodmother.png" },
    { name: "Centaur Warrunner", image: "heroes/centaur_warrunner.png" },
    { name: "Chaos Knight", image: "heroes/chaos_knight.png" },
    { name: "Chen", image: "heroes/chen.png" },
    { name: "Clinkz", image: "heroes/clinkz.png" },
    { name: "Clockwerk", image: "heroes/clockwerk.png" },
    { name: "Crystal Maiden", image: "heroes/crystal_maiden.png" },
    { name: "Dark Seer", image: "heroes/dark_seer.png" },
    { name: "Dark Willow", image: "heroes/dark_willow.png" },
    { name: "Dawnbreaker", image: "heroes/dawnbreaker.png" },
    { name: "Dazzle", image: "heroes/dazzle.png" },
    { name: "Death Prophet", image: "heroes/death_prophet.png" },
    { name: "Disruptor", image: "heroes/disruptor.png" },
    { name: "Doom", image: "heroes/doom.png" },
    { name: "Dragon Knight", image: "heroes/dragon_knight.png" },
    { name: "Drow Ranger", image: "heroes/drow_ranger.png" },
    { name: "Earth Spirit", image: "heroes/earth_spirit.png" },
    { name: "Earthshaker", image: "heroes/earthshaker.png" },
    { name: "Elder Titan", image: "heroes/elder_titan.png" },
    { name: "Ember Spirit", image: "heroes/ember_spirit.png" },
    { name: "Enchantress", image: "heroes/enchantress.png" },
    { name: "Enigma", image: "heroes/enigma.png" },
    { name: "Faceless Void", image: "heroes/faceless_void.png" },
    { name: "Grimstroke", image: "heroes/grimstroke.png" },
    { name: "Gyrocopter", image: "heroes/gyrocopter.png" },
    { name: "Hoodwink", image: "heroes/hoodwink.png" },
    { name: "Huskar", image: "heroes/huskar.png" },
    { name: "Invoker", image: "heroes/invoker.png" },
    { name: "Io", image: "heroes/io.png" },
    { name: "Jakiro", image: "heroes/jakiro.png" },
    { name: "Juggernaut", image: "heroes/juggernaut.png" },
    { name: "Keeper of the Light", image: "heroes/keeper_of_the_light.png" },
    { name: "Kez", image: "heroes/kez.png" },
    { name: "Kunkka", image: "heroes/kunkka.png" },
    { name: "Largo", image: "heroes/largo.png" },
    { name: "Legion Commander", image: "heroes/legion_commander.png" },
    { name: "Leshrac", image: "heroes/leshrac.png" },
    { name: "Lich", image: "heroes/lich.png" },
    { name: "Lifestealer", image: "heroes/lifestealer.png" },
    { name: "Lina", image: "heroes/lina.png" },
    { name: "Lion", image: "heroes/lion.png" },
    { name: "Lone Druid", image: "heroes/lone_druid.png" },
    { name: "Luna", image: "heroes/luna.png" },
    { name: "Lycan", image: "heroes/lycan.png" },
    { name: "Magnus", image: "heroes/magnus.png" },
    { name: "Marci", image: "heroes/marci.png" },
    { name: "Mars", image: "heroes/mars.png" },
    { name: "Medusa", image: "heroes/medusa.png" },
    { name: "Meepo", image: "heroes/meepo.png" },
    { name: "Mirana", image: "heroes/mirana.png" },
    { name: "Monkey King", image: "heroes/monkey_king.png" },
    { name: "Morphling", image: "heroes/morphling.png" },
    { name: "Muerta", image: "heroes/muerta.png" },
    { name: "Naga Siren", image: "heroes/naga_siren.png" },
    { name: "Nature's Prophet", image: "heroes/natures_prophet.png" },
    { name: "Necrophos", image: "heroes/necrophos.png" },
    { name: "Night Stalker", image: "heroes/night_stalker.png" },
    { name: "Nyx Assassin", image: "heroes/nyx_assassin.png" },
    { name: "Ogre Magi", image: "heroes/ogre_magi.png" },
    { name: "Omniknight", image: "heroes/omniknight.png" },
    { name: "Oracle", image: "heroes/oracle.png" },
    { name: "Outworld Destroyer", image: "heroes/outworld_destroyer.png" },
    { name: "Pangolier", image: "heroes/pangolier.png" },
    { name: "Phantom Assassin", image: "heroes/phantom_assassin.png" },
    { name: "Phantom Lancer", image: "heroes/phantom_lancer.png" },
    { name: "Phoenix", image: "heroes/phoenix.png" },
    { name: "Primal Beast", image: "heroes/primal_beast.png" },
    { name: "Puck", image: "heroes/puck.png" },
    { name: "Pudge", image: "heroes/pudge.png" },
    { name: "Pugna", image: "heroes/pugna.png" },
    { name: "Queen of Pain", image: "heroes/queen_of_pain.png" },
    { name: "Razor", image: "heroes/razor.png" },
    { name: "Riki", image: "heroes/riki.png" },
    { name: "Ringmaster", image: "heroes/ringmaster.png" },
    { name: "Rubick", image: "heroes/rubick.png" },
    { name: "Sand King", image: "heroes/sand_king.png" },
    { name: "Shadow Demon", image: "heroes/shadow_demon.png" },
    { name: "Shadow Fiend", image: "heroes/shadow_fiend.png" },
    { name: "Shadow Shaman", image: "heroes/shadow_shaman.png" },
    { name: "Silencer", image: "heroes/silencer.png" },
    { name: "Skywrath Mage", image: "heroes/skywrath_mage.png" },
    { name: "Slardar", image: "heroes/slardar.png" },
    { name: "Slark", image: "heroes/slark.png" },
    { name: "Snapfire", image: "heroes/snapfire.png" },
    { name: "Sniper", image: "heroes/sniper.png" },
    { name: "Spectre", image: "heroes/spectre.png" },
    { name: "Spirit Breaker", image: "heroes/spirit_breaker.png" },
    { name: "Storm Spirit", image: "heroes/storm_spirit.png" },
    { name: "Sven", image: "heroes/sven.png" },
    { name: "Techies", image: "heroes/techies.png" },
    { name: "Templar Assassin", image: "heroes/templar_assassin.png" },
    { name: "Terrorblade", image: "heroes/terrorblade.png" },
    { name: "Tidehunter", image: "heroes/tidehunter.png" },
    { name: "Timbersaw", image: "heroes/timbersaw.png" },
    { name: "Tinker", image: "heroes/tinker.png" },
    { name: "Tiny", image: "heroes/tiny.png" },
    { name: "Treant Protector", image: "heroes/treant_protector.png" },
    { name: "Troll Warlord", image: "heroes/troll_warlord.png" },
    { name: "Tusk", image: "heroes/tusk.png" },
    { name: "Underlord", image: "heroes/underlord.png" },
    { name: "Undying", image: "heroes/undying.png" },
    { name: "Ursa", image: "heroes/ursa.png" },
    { name: "Vengeful Spirit", image: "heroes/vengeful_spirit.png" },
    { name: "Venomancer", image: "heroes/venomancer.png" },
    { name: "Viper", image: "heroes/viper.png" },
    { name: "Visage", image: "heroes/visage.png" },
    { name: "Void Spirit", image: "heroes/void_spirit.png" },
    { name: "Warlock", image: "heroes/warlock.png" },
    { name: "Weaver", image: "heroes/weaver.png" },
    { name: "Windranger", image: "heroes/windranger.png" },
    { name: "Winter Wyvern", image: "heroes/winter_wyvern.png" },
    { name: "Witch Doctor", image: "heroes/witch_doctor.png" },
    { name: "Wraith King", image: "heroes/wraith_king.png" },
    { name: "Zeus", image: "heroes/zeus.png" }
];

// Подсчет количества героев
console.log(`Lap Fortuna загружена! Всего героев: ${heroes.length}`);

// Экспорт для использования в других файлах
if (typeof module !== 'undefined' && module.exports) {
    module.exports = heroes;
}
